---
services:
  api:
    build: .
    depends_on:
      - extra-source
    environment:
      PORT: 8090
      JOBBERWOCKY_URL: http://extra-source
    ports:
      - "8090:8090"
    networks:
      - backend
      - extra

  extra-source:
    build:
      context: ./jobberwocky-extra-source
    ports:
      - "8080:8080"
    networks:
      - extra

networks:
  backend:
  extra:
