---
services:
  api:
    build: .
    depends_on:
      - extra-source
    environment:
      PORT: 8090
      JOBBERWOCKY_URL: http://extra-source:8080
    ports:
      - "8090:8090"
    links:
      - "extra-source"

  extra-source:
    build:
      context: ./jobberwocky-extra-source
    ports:
      - "8080:8080"
